import React,{useState} from 'react';
import {Alert,ScrollView,Switch,Text,View} from 'react-native';
import {riskApi} from '../api/client';
import {Button,Card,Field,H,P,Screen} from '../components/UI';
export default function DisputeScreen({route}:any){
 const[n,setN]=useState(''),[e,setE]=useState(''),[s,setS]=useState(''),[med,setMed]=useState(true),[prac,setPrac]=useState(true),[busy,setBusy]=useState(false);
 const go=async()=>{const name=n.trim(),email=e.trim().toLowerCase(),summary=s.trim(); if(!String(route.params?.id||''))return Alert.alert('Record required','Return to the record and open the dispute again.'); if(name.length<2)return Alert.alert('Name required','Enter your full name.'); if(!/^\S+@\S+\.\S+$/.test(email))return Alert.alert('Valid email required','Enter a valid email address.'); if(summary.length<20)return Alert.alert('More detail required','Provide at least 20 characters explaining the correction you seek.'); try{setBusy(true);const f=new FormData();f.append('claimantName',name);f.append('claimantEmail',email);f.append('disputeType','ACCURACY_OR_CONTEXT');f.append('summary',summary);f.append('country','NG');f.append('termsVersion','blacklist-terms-v1');f.append('mediationRequested',String(med));f.append('practitionerInvolvementRequested',String(prac));f.append('practitionerType','MEDIATOR');const d=await riskApi.dispute(String(route.params.id),f);Alert.alert('Dispute opened',d?.message||'Your response has been recorded.');}catch(x:any){Alert.alert('Could not submit',x?.message||'Unable to submit the dispute.');}finally{setBusy(false);}};
 return <ScrollView><Screen><H>Dispute or correction</H><P>Use this route if you are the subject, representative, or otherwise have a legitimate basis to challenge accuracy, completeness, context or identity.</P><Card><Field placeholder="Your full name" value={n} onChangeText={setN}/><Field placeholder="Email" autoCapitalize="none" keyboardType="email-address" value={e} onChangeText={setE}/><Field multiline style={{minHeight:130,textAlignVertical:'top'}} placeholder="Explain what is inaccurate or missing and the correction you seek" value={s} onChangeText={setS}/><View style={{flexDirection:'row',gap:10,alignItems:'center'}}><Switch value={med} onValueChange={setMed}/><Text>Request mediation</Text></View><View style={{flexDirection:'row',gap:10,alignItems:'center'}}><Switch value={prac} onValueChange={setPrac}/><Text>Request practitioner involvement</Text></View><Button title={busy?'Submitting…':'Submit dispute'} disabled={busy} onPress={go}/></Card></Screen></ScrollView>;
}
