import React,{useState} from 'react';
import {Alert,ScrollView,Text} from 'react-native';
import {riskApi} from '../api/client';
import {Button,Card,Field,H,P,Screen} from '../components/UI';
export default function RemovalScreen({route}:any){
 const[r,setR]=useState(''),[preview,setPreview]=useState<any>(),[busy,setBusy]=useState(false),[submitted,setSubmitted]=useState(false); const id=String(route.params?.id||'');
 const loadPreview=async()=>{if(!id)return Alert.alert('Record required','Return to the record and open resolution review again.');try{setPreview(await riskApi.removalPreview(id));}catch(x:any){Alert.alert('Unavailable',x?.message||'Fee preview is unavailable.');}};
 const submit=async()=>{const reason=r.trim();if(!id)return Alert.alert('Record required','Return to the record and open resolution review again.');if(reason.length<20)return Alert.alert('More detail required','Explain the correction or removal basis in at least 20 characters.');try{setBusy(true);const d=await riskApi.removalRequest(id,{reason,country:'NG',termsVersion:'blacklist-terms-v1'});setSubmitted(true);Alert.alert('Review request submitted',d?.message||'Your request has entered administrative review.');}catch(x:any){Alert.alert('Could not submit',x?.message||'Unable to submit the review request.');}finally{setBusy(false);}};
 return <ScrollView><Screen><H>Resolution review</H><P>This does not promise deletion in exchange for payment. Removal/correction depends on review, legal basis, accuracy and retention requirements.</P><Card>{preview?<><Text>Configured fee preview: {preview.finalAmount||preview.amount||'—'} {preview.selectedCurrency||preview.currency||'NGN'}</Text><P>A fee must never be represented as buying innocence, erasing a valid legal record, or guaranteeing removal.</P></>:<Button title="Load backend fee preview" kind="secondary" onPress={loadPreview}/>}<Field multiline style={{minHeight:120,textAlignVertical:'top'}} placeholder="Reason for correction/removal request" value={r} onChangeText={setR}/><Button title={busy?'Submitting…':'Submit review request (no payment)'} disabled={busy||submitted} onPress={submit}/>{submitted?<P>Your request has been submitted for administrative review.</P>:null}</Card></Screen></ScrollView>;
}
