import React,{useEffect,useState} from 'react'; import {Alert,ScrollView,Switch,Text,View} from 'react-native'; import * as ImagePicker from 'expo-image-picker'; import * as DocumentPicker from 'expo-document-picker'; import {riskApi} from '../api/client'; import {Button,Card,Field,H,P,Screen} from '../components/UI';
const CATS=['FRAUD_OR_SCAM','UNPAID_OBLIGATION','CONTRACT_NONPERFORMANCE','PROPERTY_OR_ASSET_DISPUTE','BUSINESS_MISCONDUCT','EMPLOYMENT_OR_PROFESSIONAL','IMPERSONATION_OR_IDENTITY','OTHER'];
export default function ReportScreen(){const[n,setN]=useState('');const[reason,setReason]=useState('');const[category,setCategory]=useState('OTHER');const[email,setEmail]=useState('');const[consent,setConsent]=useState(false);const[terms,setTerms]=useState<any>();const[files,setFiles]=useState<any[]>([]);useEffect(()=>{riskApi.terms().then(setTerms).catch(()=>{})},[]);const addImage=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8});if(!r.canceled)setFiles(v=>[...v,...r.assets])};const addDoc=async()=>{const r=await DocumentPicker.getDocumentAsync({multiple:true,copyToCacheDirectory:true});if(!r.canceled)setFiles(v=>[...v,...r.assets])};const submit=async()=>{if(!consent)return Alert.alert('Confirmation required','Confirm that the report is made in good faith and may be challenged.');if(!n.trim()||reason.trim().length<20)return Alert.alert('More detail required','Provide the subject and a factual summary of at least 20 characters.');try{const f=new FormData();f.append('name',n.trim());f.append('category',category);f.append('severity','MEDIUM');f.append('reason',reason.trim());f.append('country','NG');f.append('termsVersion',terms?.termsVersion||'blacklist-terms-v1');f.append('publicationConsent','false');f.append('subjectEmail',email.trim());for(const x of files)f.append('files',{uri:x.uri,name:x.fileName||x.name||'evidence.jpg',type:x.mimeType||'image/jpeg'} as any);const d=await riskApi.submit(f);Alert.alert('Report received',`Reference: ${d.id||d._id||'created'}

Your submission enters the Integres review process. Submission or payment does not automatically make it public.`);setN('');setReason('');setFiles([]);setConsent(false)}catch(x:any){Alert.alert('Submission failed',x.message)}};return <ScrollView><Screen><H>Submit a Blacklist report</H><P>Report a documented dispute, suspected fraud/scam, unpaid obligation, non-performance or other accountability concern. State observable facts and attach relevant evidence.</P><Card><Text style={{fontWeight:'900'}}>Report category</Text><P>{CATS.join(' · ')}</P><Field placeholder="Category code (e.g. FRAUD_OR_SCAM)" value={category} onChangeText={setCategory}/><Field placeholder="Person or company being reported" value={n} onChangeText={setN}/><Field placeholder="Subject email for notice, if known" autoCapitalize="none" value={email} onChangeText={setEmail}/><Field multiline style={{minHeight:140,textAlignVertical:'top'}} placeholder="What happened? Include dates, amounts, obligations, actions taken and the evidence you can support." value={reason} onChangeText={setReason}/><P>Evidence attached: {files.length}</P><Button title="Add image evidence" kind="secondary" onPress={addImage}/><Button title="Add document evidence" kind="secondary" onPress={addDoc}/></Card><Card><Text style={{fontWeight:'900'}}>What happens next</Text><P>1. Report received confidentially.
2. Due-diligence/moderation review.
3. Subject notice/right to respond where required.
4. Decision on public eligibility.
5. Dispute, correction, mediation or resolution remains available.</P></Card><Card><View style={{flexDirection:'row',gap:10,alignItems:'center'}}><Switch value={consent} onValueChange={setConsent}/><Text style={{flex:1}}>I am reporting in good faith. I will not use Blacklist for harassment, revenge, threats or doxxing, and I understand the subject may challenge this report.</Text></View></Card><Button title="Submit report for review" onPress={submit}/></Screen></ScrollView>}
